@echo off
REM Script to start the EcoScorer project

echo Starting EcoScorer Project...
echo.

echo Setting up server...
cd server
echo Installing server dependencies...
npm install > nul 2>&1
if %ERRORLEVEL% NEQ 0 echo Warning: Error installing server dependencies, continuing anyway...

echo Generating Prisma client...
npx prisma generate > nul 2>&1
if %ERRORLEVEL% NEQ 0 echo Warning: Error generating Prisma client, continuing anyway...

echo Starting server on port 3001...
start cmd /k "npm run dev"

timeout /t 5 /nobreak > nul

echo.
echo Setting up client...
cd ..\client
echo Installing client dependencies...
npm install > nul 2>&1
if %ERRORLEVEL% NEQ 0 echo Warning: Error installing client dependencies, continuing anyway...

echo Starting client on port 5173...
start cmd /k "npm run dev"

echo.
echo The application is now running!
echo - Client: http://localhost:5173
echo - Server: http://localhost:3001
echo.
echo Press any key to exit...
pause > nul